// Central Plant Database
// Single source of truth for all plant data used across the application

export type WaterNeed = "very-low" | "low" | "medium" | "high" | "very-high";
export type SunNeed = "shade" | "partial-shade" | "partial-sun" | "full-sun";
export type SoilType = "sandy" | "loamy" | "clay" | "any";
export type SaltTolerance = "none" | "low" | "medium" | "high";
export type Difficulty = "easy" | "medium" | "hard";
export type PlantCategory = "vegetable" | "fruit" | "legume" | "root" | "herb" | "leafy-green" | "grain" | "tuber";
export type GrowingSpace = "containers" | "rooftop" | "balcony" | "backyard" | "microplot" | "field";
export type Goal = "calories" | "nutrition" | "fast" | "income";
export type GrowthStage = "seedling" | "vegetative" | "flowering" | "fruiting" | "mature";

export interface PlantData {
    id: string;
    name: string;
    category: PlantCategory;
    scientificName?: string;
    description?: string;

    // Growing requirements
    waterNeed: WaterNeed;
    sunNeed: SunNeed;
    preferredSoil: SoilType[];
    saltTolerance: SaltTolerance;
    minTemperatureC: number;
    maxTemperatureC: number;
    optimalTemperatureC: { min: number; max: number };

    // Space and difficulty
    spaceEfficiency: GrowingSpace[];
    difficulty: Difficulty;
    spacingCm: number; // spacing between plants in cm
    depthCm: number; // planting depth in cm

    // Timing
    germinationDays: { min: number; max: number };
    harvestDays: { min: number; max: number };
    seasonalPlanting?: string[]; // e.g., ["spring", "fall"]

    // Water calculations (liters per day per plant)
    waterByStage: {
        seedling: number;
        vegetative: number;
        flowering: number;
        fruiting: number;
        mature: number;
    };

    // Yield and nutrition
    expectedYieldKg?: number; // per plant
    caloriesPer100g?: number;
    nutritionHighlights?: string[];

    // Goals this plant serves
    goalFit: Goal[];

    // Companion planting
    companions?: string[]; // plant IDs that grow well together
    avoid?: string[]; // plant IDs to avoid planting nearby

    // Additional notes
    tips?: string[];
    commonPests?: string[];
    commonDiseases?: string[];
}

// Complete plant database
export const PLANTS: Record<string, PlantData> = {
    // === VEGETABLES ===
    tomato: {
        id: "tomato",
        name: "Tomato",
        category: "vegetable",
        scientificName: "Solanum lycopersicum",
        description: "Versatile fruit used as vegetable, rich in vitamins",
        waterNeed: "high",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 10,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 20, max: 30 },
        spaceEfficiency: ["containers", "rooftop", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 60,
        depthCm: 1,
        germinationDays: { min: 5, max: 10 },
        harvestDays: { min: 60, max: 80 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.5,
            flowering: 0.8,
            fruiting: 1.0,
            mature: 0.7,
        },
        expectedYieldKg: 4,
        caloriesPer100g: 18,
        nutritionHighlights: ["Vitamin C", "Lycopene", "Potassium"],
        goalFit: ["nutrition"],
        companions: ["basil", "carrot", "parsley"],
        avoid: ["cabbage", "fennel"],
        tips: ["Stake or cage for support", "Remove suckers for larger fruit"],
        commonPests: ["Aphids", "Hornworms", "Whiteflies"],
        commonDiseases: ["Blight", "Blossom end rot"],
    },

    cucumber: {
        id: "cucumber",
        name: "Cucumber",
        category: "vegetable",
        scientificName: "Cucumis sativus",
        description: "Refreshing vegetable, great for salads",
        waterNeed: "high",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 20, max: 30 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 45,
        depthCm: 2,
        germinationDays: { min: 3, max: 10 },
        harvestDays: { min: 50, max: 70 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.3,
            vegetative: 0.6,
            flowering: 0.9,
            fruiting: 1.2,
            mature: 0.8,
        },
        expectedYieldKg: 3,
        caloriesPer100g: 16,
        nutritionHighlights: ["Hydration", "Vitamin K", "Potassium"],
        goalFit: ["nutrition", "fast"],
        companions: ["beans", "peas", "radish"],
        avoid: ["potato", "aromatic-herbs"],
        tips: ["Provide trellis for vertical growing", "Harvest young for best taste"],
        commonPests: ["Cucumber beetles", "Aphids"],
        commonDiseases: ["Powdery mildew", "Mosaic virus"],
    },

    pepper: {
        id: "pepper",
        name: "Bell Pepper",
        category: "vegetable",
        scientificName: "Capsicum annuum",
        description: "Sweet peppers in various colors",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 21, max: 29 },
        spaceEfficiency: ["containers", "rooftop", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 45,
        depthCm: 0.5,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 60, max: 90 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.15,
            vegetative: 0.4,
            flowering: 0.6,
            fruiting: 0.7,
            mature: 0.5,
        },
        expectedYieldKg: 2,
        caloriesPer100g: 31,
        nutritionHighlights: ["Vitamin C", "Vitamin A", "Antioxidants"],
        goalFit: ["nutrition"],
        companions: ["tomato", "basil", "carrot"],
        avoid: ["fennel"],
        tips: ["Start indoors in cooler climates", "Pick regularly to encourage more fruit"],
        commonPests: ["Aphids", "Spider mites"],
        commonDiseases: ["Bacterial spot", "Blossom end rot"],
    },

    eggplant: {
        id: "eggplant",
        name: "Eggplant",
        category: "vegetable",
        scientificName: "Solanum melongena",
        description: "Purple vegetable great for grilling and stews",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 22, max: 30 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 60,
        depthCm: 0.5,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 70, max: 85 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.5,
            flowering: 0.7,
            fruiting: 0.8,
            mature: 0.6,
        },
        expectedYieldKg: 3,
        caloriesPer100g: 25,
        nutritionHighlights: ["Fiber", "Antioxidants", "B Vitamins"],
        goalFit: ["nutrition"],
        companions: ["pepper", "beans"],
        avoid: ["fennel"],
        tips: ["Requires warm soil", "Mulch to retain moisture"],
        commonPests: ["Flea beetles", "Aphids"],
        commonDiseases: ["Verticillium wilt"],
    },

    zucchini: {
        id: "zucchini",
        name: "Zucchini",
        category: "vegetable",
        scientificName: "Cucurbita pepo",
        description: "Prolific summer squash",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 18, max: 28 },
        spaceEfficiency: ["backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 90,
        depthCm: 2,
        germinationDays: { min: 5, max: 10 },
        harvestDays: { min: 45, max: 65 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.3,
            vegetative: 0.6,
            flowering: 0.8,
            fruiting: 1.0,
            mature: 0.7,
        },
        expectedYieldKg: 5,
        caloriesPer100g: 17,
        nutritionHighlights: ["Vitamin C", "Potassium", "Fiber"],
        goalFit: ["calories", "fast"],
        companions: ["beans", "corn"],
        avoid: ["potato"],
        tips: ["Harvest when 15-20cm for best flavor", "Very productive plant"],
        commonPests: ["Squash bugs", "Vine borers"],
        commonDiseases: ["Powdery mildew"],
    },

    pumpkin: {
        id: "pumpkin",
        name: "Pumpkin",
        category: "vegetable",
        scientificName: "Cucurbita maxima",
        description: "Large squash, stores well for months",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 18, max: 30 },
        spaceEfficiency: ["backyard", "field"],
        difficulty: "medium",
        spacingCm: 150,
        depthCm: 3,
        germinationDays: { min: 5, max: 10 },
        harvestDays: { min: 90, max: 120 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.4,
            vegetative: 0.8,
            flowering: 1.2,
            fruiting: 1.5,
            mature: 0.5,
        },
        expectedYieldKg: 8,
        caloriesPer100g: 26,
        nutritionHighlights: ["Vitamin A", "Fiber", "Potassium"],
        goalFit: ["calories"],
        companions: ["corn", "beans"],
        avoid: ["potato"],
        tips: ["Needs lots of space", "Great for storage"],
        commonPests: ["Squash bugs", "Cucumber beetles"],
        commonDiseases: ["Powdery mildew"],
    },

    cabbage: {
        id: "cabbage",
        name: "Cabbage",
        category: "vegetable",
        scientificName: "Brassica oleracea var. capitata",
        description: "Hardy leafy vegetable, stores well",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy", "clay"],
        saltTolerance: "medium",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 15, max: 20 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 45,
        depthCm: 1,
        germinationDays: { min: 4, max: 10 },
        harvestDays: { min: 70, max: 100 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.5,
            flowering: 0.5,
            fruiting: 0.5,
            mature: 0.4,
        },
        expectedYieldKg: 2,
        caloriesPer100g: 25,
        nutritionHighlights: ["Vitamin C", "Vitamin K", "Fiber"],
        goalFit: ["nutrition", "calories"],
        companions: ["beans", "celery", "onion"],
        avoid: ["tomato", "strawberry"],
        tips: ["Tolerates light frost", "Great for fermentation"],
        commonPests: ["Cabbage worms", "Aphids"],
        commonDiseases: ["Clubroot", "Black rot"],
    },

    broccoli: {
        id: "broccoli",
        name: "Broccoli",
        category: "vegetable",
        scientificName: "Brassica oleracea var. italica",
        description: "Nutrient-dense florets",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 15, max: 20 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 45,
        depthCm: 1,
        germinationDays: { min: 4, max: 10 },
        harvestDays: { min: 60, max: 90 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.5,
            flowering: 0.6,
            fruiting: 0.6,
            mature: 0.4,
        },
        expectedYieldKg: 0.5,
        caloriesPer100g: 34,
        nutritionHighlights: ["Vitamin C", "Vitamin K", "Folate"],
        goalFit: ["nutrition"],
        companions: ["onion", "celery", "potato"],
        avoid: ["tomato", "strawberry"],
        tips: ["Harvest before flowers open", "Side shoots continue producing"],
        commonPests: ["Cabbage worms", "Aphids"],
        commonDiseases: ["Clubroot"],
    },

    cauliflower: {
        id: "cauliflower",
        name: "Cauliflower",
        category: "vegetable",
        scientificName: "Brassica oleracea var. botrytis",
        description: "Mild-flavored cruciferous vegetable",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 15, max: 20 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "hard",
        spacingCm: 60,
        depthCm: 1,
        germinationDays: { min: 4, max: 10 },
        harvestDays: { min: 70, max: 100 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.5,
            flowering: 0.6,
            fruiting: 0.6,
            mature: 0.4,
        },
        expectedYieldKg: 1,
        caloriesPer100g: 25,
        nutritionHighlights: ["Vitamin C", "Vitamin K", "Folate"],
        goalFit: ["nutrition"],
        companions: ["beans", "celery"],
        avoid: ["tomato", "strawberry"],
        tips: ["Blanch by tying leaves over head", "Sensitive to temperature"],
        commonPests: ["Cabbage worms", "Aphids"],
        commonDiseases: ["Clubroot"],
    },

    // === LEAFY GREENS ===
    lettuce: {
        id: "lettuce",
        name: "Lettuce",
        category: "leafy-green",
        scientificName: "Lactuca sativa",
        description: "Fast-growing salad green",
        waterNeed: "medium",
        sunNeed: "partial-shade",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 15, max: 20 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 25,
        depthCm: 0.5,
        germinationDays: { min: 2, max: 8 },
        harvestDays: { min: 30, max: 60 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.25,
            fruiting: 0.25,
            mature: 0.2,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 15,
        nutritionHighlights: ["Vitamin A", "Vitamin K", "Folate"],
        goalFit: ["nutrition", "fast"],
        companions: ["carrot", "radish", "strawberry"],
        avoid: ["celery"],
        tips: ["Succession plant for continuous harvest", "Bolts in heat"],
        commonPests: ["Aphids", "Slugs"],
        commonDiseases: ["Downy mildew"],
    },

    spinach: {
        id: "spinach",
        name: "Spinach",
        category: "leafy-green",
        scientificName: "Spinacia oleracea",
        description: "Iron-rich leafy green",
        waterNeed: "medium",
        sunNeed: "partial-shade",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 2,
        maxTemperatureC: 24,
        optimalTemperatureC: { min: 10, max: 20 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 15,
        depthCm: 1,
        germinationDays: { min: 5, max: 14 },
        harvestDays: { min: 35, max: 50 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.2,
            flowering: 0.2,
            fruiting: 0.2,
            mature: 0.15,
        },
        expectedYieldKg: 0.25,
        caloriesPer100g: 23,
        nutritionHighlights: ["Iron", "Vitamin A", "Vitamin K", "Folate"],
        goalFit: ["nutrition", "fast"],
        companions: ["strawberry", "peas"],
        avoid: [],
        tips: ["Prefers cool weather", "Cut-and-come-again harvesting"],
        commonPests: ["Aphids", "Leaf miners"],
        commonDiseases: ["Downy mildew"],
    },

    kale: {
        id: "kale",
        name: "Kale",
        category: "leafy-green",
        scientificName: "Brassica oleracea var. sabellica",
        description: "Hardy, nutritious leafy green",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "medium",
        minTemperatureC: -5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 22 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 40,
        depthCm: 1,
        germinationDays: { min: 5, max: 10 },
        harvestDays: { min: 50, max: 70 },
        seasonalPlanting: ["spring", "fall", "winter"],
        waterByStage: {
            seedling: 0.15,
            vegetative: 0.3,
            flowering: 0.3,
            fruiting: 0.3,
            mature: 0.25,
        },
        expectedYieldKg: 0.5,
        caloriesPer100g: 49,
        nutritionHighlights: ["Vitamin K", "Vitamin A", "Vitamin C", "Calcium"],
        goalFit: ["nutrition"],
        companions: ["beans", "celery", "onion"],
        avoid: ["tomato", "strawberry"],
        tips: ["Frost improves flavor", "Very cold hardy"],
        commonPests: ["Cabbage worms", "Aphids"],
        commonDiseases: ["Clubroot"],
    },

    swissChard: {
        id: "swissChard",
        name: "Swiss Chard",
        category: "leafy-green",
        scientificName: "Beta vulgaris subsp. vulgaris",
        description: "Colorful, heat-tolerant green",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "medium",
        minTemperatureC: 5,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 30,
        depthCm: 1,
        germinationDays: { min: 5, max: 14 },
        harvestDays: { min: 50, max: 60 },
        seasonalPlanting: ["spring", "summer", "fall"],
        waterByStage: {
            seedling: 0.15,
            vegetative: 0.3,
            flowering: 0.3,
            fruiting: 0.3,
            mature: 0.25,
        },
        expectedYieldKg: 0.5,
        caloriesPer100g: 19,
        nutritionHighlights: ["Vitamin K", "Vitamin A", "Magnesium"],
        goalFit: ["nutrition"],
        companions: ["beans", "cabbage", "onion"],
        avoid: [],
        tips: ["More heat tolerant than spinach", "Harvest outer leaves first"],
        commonPests: ["Leaf miners", "Aphids"],
        commonDiseases: ["Cercospora leaf spot"],
    },

    arugula: {
        id: "arugula",
        name: "Arugula",
        category: "leafy-green",
        scientificName: "Eruca vesicaria",
        description: "Peppery salad green",
        waterNeed: "low",
        sunNeed: "partial-shade",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 10, max: 20 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 15,
        depthCm: 0.5,
        germinationDays: { min: 3, max: 7 },
        harvestDays: { min: 20, max: 40 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 25,
        nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate"],
        goalFit: ["fast", "nutrition"],
        companions: ["lettuce", "spinach"],
        avoid: [],
        tips: ["Quick to bolt in heat", "Very fast growing"],
        commonPests: ["Flea beetles"],
        commonDiseases: ["Downy mildew"],
    },

    bokChoy: {
        id: "bokChoy",
        name: "Bok Choy",
        category: "leafy-green",
        scientificName: "Brassica rapa subsp. chinensis",
        description: "Asian leafy vegetable",
        waterNeed: "medium",
        sunNeed: "partial-shade",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 15, max: 20 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 25,
        depthCm: 0.5,
        germinationDays: { min: 4, max: 8 },
        harvestDays: { min: 30, max: 50 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.25,
            fruiting: 0.25,
            mature: 0.2,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 13,
        nutritionHighlights: ["Vitamin C", "Vitamin A", "Calcium"],
        goalFit: ["fast", "nutrition"],
        companions: ["beans", "celery"],
        avoid: ["tomato", "strawberry"],
        tips: ["Harvest baby or full size", "Cool weather crop"],
        commonPests: ["Flea beetles", "Aphids"],
        commonDiseases: ["Clubroot"],
    },

    // === LEGUMES ===
    beans: {
        id: "beans",
        name: "Beans (Green/String)",
        category: "legume",
        scientificName: "Phaseolus vulgaris",
        description: "Easy-growing, nitrogen-fixing legume",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "medium",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 20, max: 28 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 10,
        depthCm: 3,
        germinationDays: { min: 5, max: 10 },
        harvestDays: { min: 50, max: 65 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.15,
            vegetative: 0.3,
            flowering: 0.5,
            fruiting: 0.5,
            mature: 0.3,
        },
        expectedYieldKg: 1.5,
        caloriesPer100g: 31,
        nutritionHighlights: ["Protein", "Fiber", "Vitamin K", "Folate"],
        goalFit: ["calories", "nutrition"],
        companions: ["corn", "cucumber", "carrot"],
        avoid: ["onion", "garlic"],
        tips: ["Fix nitrogen in soil", "Pick regularly for more production"],
        commonPests: ["Mexican bean beetles", "Aphids"],
        commonDiseases: ["Bean rust", "Mosaic virus"],
    },

    peas: {
        id: "peas",
        name: "Peas",
        category: "legume",
        scientificName: "Pisum sativum",
        description: "Cool-weather climbing legume",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 24,
        optimalTemperatureC: { min: 13, max: 18 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 8,
        depthCm: 3,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 55, max: 70 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.4,
            fruiting: 0.4,
            mature: 0.25,
        },
        expectedYieldKg: 0.5,
        caloriesPer100g: 81,
        nutritionHighlights: ["Protein", "Fiber", "Vitamin C", "Vitamin K"],
        goalFit: ["nutrition", "calories"],
        companions: ["carrot", "radish", "cucumber"],
        avoid: ["onion", "garlic"],
        tips: ["Provide support for climbing", "Plant early in spring"],
        commonPests: ["Aphids", "Pea weevils"],
        commonDiseases: ["Powdery mildew"],
    },

    lentils: {
        id: "lentils",
        name: "Lentils",
        category: "legume",
        scientificName: "Lens culinaris",
        description: "Drought-tolerant protein source",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "medium",
        minTemperatureC: 5,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["backyard", "microplot", "field"],
        difficulty: "easy",
        spacingCm: 10,
        depthCm: 3,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 80, max: 110 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.2,
            flowering: 0.3,
            fruiting: 0.25,
            mature: 0.1,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 353,
        nutritionHighlights: ["Protein", "Fiber", "Iron", "Folate"],
        goalFit: ["calories", "nutrition"],
        companions: ["cucumber", "potato"],
        avoid: ["onion", "garlic"],
        tips: ["Very drought tolerant", "Let dry on plant before harvest"],
        commonPests: ["Aphids"],
        commonDiseases: ["Ascochyta blight"],
    },

    chickpeas: {
        id: "chickpeas",
        name: "Chickpeas",
        category: "legume",
        scientificName: "Cicer arietinum",
        description: "Drought-tolerant, high-protein legume",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "medium",
        minTemperatureC: 10,
        maxTemperatureC: 32,
        optimalTemperatureC: { min: 18, max: 26 },
        spaceEfficiency: ["backyard", "microplot", "field"],
        difficulty: "medium",
        spacingCm: 15,
        depthCm: 5,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 90, max: 120 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.15,
            vegetative: 0.25,
            flowering: 0.35,
            fruiting: 0.3,
            mature: 0.1,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 364,
        nutritionHighlights: ["Protein", "Fiber", "Iron", "Manganese"],
        goalFit: ["calories", "nutrition"],
        companions: ["corn", "squash"],
        avoid: ["onion", "garlic"],
        tips: ["Very drought tolerant", "Long growing season"],
        commonPests: ["Pod borers"],
        commonDiseases: ["Ascochyta blight"],
    },

    // === ROOTS & TUBERS ===
    carrot: {
        id: "carrot",
        name: "Carrot",
        category: "root",
        scientificName: "Daucus carota",
        description: "Sweet root vegetable, rich in beta-carotene",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 22 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 5,
        depthCm: 0.5,
        germinationDays: { min: 10, max: 21 },
        harvestDays: { min: 60, max: 80 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.25,
            fruiting: 0.25,
            mature: 0.2,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 41,
        nutritionHighlights: ["Vitamin A", "Beta-carotene", "Fiber"],
        goalFit: ["nutrition"],
        companions: ["lettuce", "tomato", "onion"],
        avoid: ["dill"],
        tips: ["Needs loose, rock-free soil", "Thin seedlings early"],
        commonPests: ["Carrot fly", "Aphids"],
        commonDiseases: ["Leaf blight"],
    },

    radish: {
        id: "radish",
        name: "Radish",
        category: "root",
        scientificName: "Raphanus sativus",
        description: "Fast-growing peppery root",
        waterNeed: "low",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 10, max: 18 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 5,
        depthCm: 1,
        germinationDays: { min: 3, max: 7 },
        harvestDays: { min: 20, max: 30 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.1,
        caloriesPer100g: 16,
        nutritionHighlights: ["Vitamin C", "Folate"],
        goalFit: ["fast"],
        companions: ["lettuce", "peas", "cucumber"],
        avoid: [],
        tips: ["Fastest vegetable to harvest", "Great for beginners"],
        commonPests: ["Flea beetles"],
        commonDiseases: ["Clubroot"],
    },

    beet: {
        id: "beet",
        name: "Beet",
        category: "root",
        scientificName: "Beta vulgaris",
        description: "Dual-purpose: edible root and greens",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "medium",
        minTemperatureC: 5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 22 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 10,
        depthCm: 1,
        germinationDays: { min: 5, max: 14 },
        harvestDays: { min: 50, max: 70 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.25,
            fruiting: 0.25,
            mature: 0.2,
        },
        expectedYieldKg: 0.25,
        caloriesPer100g: 43,
        nutritionHighlights: ["Folate", "Manganese", "Potassium"],
        goalFit: ["nutrition", "calories"],
        companions: ["onion", "cabbage", "lettuce"],
        avoid: ["beans"],
        tips: ["Greens are also edible and nutritious", "Store well in cool conditions"],
        commonPests: ["Leaf miners"],
        commonDiseases: ["Cercospora leaf spot"],
    },

    potato: {
        id: "potato",
        name: "Potato",
        category: "tuber",
        scientificName: "Solanum tuberosum",
        description: "Staple calorie crop, stores well",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 22 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 30,
        depthCm: 10,
        germinationDays: { min: 14, max: 21 },
        harvestDays: { min: 70, max: 120 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.4,
            flowering: 0.6,
            fruiting: 0.6,
            mature: 0.3,
        },
        expectedYieldKg: 2,
        caloriesPer100g: 77,
        nutritionHighlights: ["Potassium", "Vitamin C", "Vitamin B6"],
        goalFit: ["calories"],
        companions: ["beans", "cabbage", "corn"],
        avoid: ["tomato", "cucumber"],
        tips: ["Hill soil around stems as they grow", "Cure before storage"],
        commonPests: ["Colorado potato beetle", "Aphids"],
        commonDiseases: ["Late blight", "Scab"],
    },

    sweetPotato: {
        id: "sweetPotato",
        name: "Sweet Potato",
        category: "tuber",
        scientificName: "Ipomoea batatas",
        description: "Nutritious, heat-loving tuber",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "medium",
        minTemperatureC: 20,
        maxTemperatureC: 38,
        optimalTemperatureC: { min: 24, max: 32 },
        spaceEfficiency: ["backyard", "microplot", "field"],
        difficulty: "medium",
        spacingCm: 40,
        depthCm: 8,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 90, max: 150 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.2,
            vegetative: 0.4,
            flowering: 0.5,
            fruiting: 0.5,
            mature: 0.3,
        },
        expectedYieldKg: 2,
        caloriesPer100g: 86,
        nutritionHighlights: ["Vitamin A", "Fiber", "Potassium"],
        goalFit: ["calories", "nutrition"],
        companions: ["beans", "corn"],
        avoid: ["squash"],
        tips: ["Needs long warm season", "Cure for sweeter flavor"],
        commonPests: ["Sweet potato weevil"],
        commonDiseases: ["Fusarium wilt"],
    },

    turnip: {
        id: "turnip",
        name: "Turnip",
        category: "root",
        scientificName: "Brassica rapa subsp. rapa",
        description: "Fast-growing root with edible greens",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 24,
        optimalTemperatureC: { min: 12, max: 20 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 10,
        depthCm: 1,
        germinationDays: { min: 3, max: 10 },
        harvestDays: { min: 40, max: 60 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.25,
            fruiting: 0.25,
            mature: 0.2,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 28,
        nutritionHighlights: ["Vitamin C", "Fiber"],
        goalFit: ["fast", "calories"],
        companions: ["peas", "beans"],
        avoid: ["potato"],
        tips: ["Greens are nutritious", "Best in cool weather"],
        commonPests: ["Flea beetles", "Aphids"],
        commonDiseases: ["Clubroot"],
    },

    // === ALLIUMS ===
    onion: {
        id: "onion",
        name: "Onion",
        category: "vegetable",
        scientificName: "Allium cepa",
        description: "Essential cooking ingredient, stores well",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "medium",
        minTemperatureC: 5,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 10,
        depthCm: 2,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 90, max: 120 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.2,
            flowering: 0.15,
            fruiting: 0.15,
            mature: 0.1,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 40,
        nutritionHighlights: ["Vitamin C", "Quercetin", "Fiber"],
        goalFit: ["calories"],
        companions: ["carrot", "lettuce", "tomato"],
        avoid: ["beans", "peas"],
        tips: ["Stop watering when tops fall over", "Cure before storage"],
        commonPests: ["Onion thrips", "Onion maggots"],
        commonDiseases: ["Downy mildew", "Pink root"],
    },

    garlic: {
        id: "garlic",
        name: "Garlic",
        category: "vegetable",
        scientificName: "Allium sativum",
        description: "Flavorful, medicinal bulb",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "medium",
        minTemperatureC: -5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 12, max: 20 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 15,
        depthCm: 5,
        germinationDays: { min: 14, max: 21 },
        harvestDays: { min: 180, max: 270 },
        seasonalPlanting: ["fall"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.2,
            flowering: 0.15,
            fruiting: 0.15,
            mature: 0.05,
        },
        expectedYieldKg: 0.05,
        caloriesPer100g: 149,
        nutritionHighlights: ["Allicin", "Vitamin C", "Manganese"],
        goalFit: ["nutrition"],
        companions: ["tomato", "pepper", "carrot"],
        avoid: ["beans", "peas"],
        tips: ["Plant in fall for summer harvest", "Very long storage life"],
        commonPests: ["Onion maggots"],
        commonDiseases: ["White rot"],
    },

    leek: {
        id: "leek",
        name: "Leek",
        category: "vegetable",
        scientificName: "Allium ampeloprasum",
        description: "Mild onion flavor, cold hardy",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: -5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 12, max: 20 },
        spaceEfficiency: ["containers", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 15,
        depthCm: 2,
        germinationDays: { min: 10, max: 21 },
        harvestDays: { min: 100, max: 150 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.25,
            flowering: 0.2,
            fruiting: 0.2,
            mature: 0.15,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 61,
        nutritionHighlights: ["Vitamin K", "Vitamin C", "Folate"],
        goalFit: ["nutrition"],
        companions: ["carrot", "celery"],
        avoid: ["beans", "peas"],
        tips: ["Hill soil around stems for white portions", "Very cold tolerant"],
        commonPests: ["Onion thrips", "Leek moth"],
        commonDiseases: ["Rust"],
    },

    scallion: {
        id: "scallion",
        name: "Scallion/Green Onion",
        category: "vegetable",
        scientificName: "Allium fistulosum",
        description: "Quick-growing mild onion",
        waterNeed: "low",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "medium",
        minTemperatureC: 5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 24 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 5,
        depthCm: 1,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 30, max: 60 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.1,
        caloriesPer100g: 32,
        nutritionHighlights: ["Vitamin K", "Vitamin C"],
        goalFit: ["fast"],
        companions: ["carrot", "lettuce"],
        avoid: ["beans", "peas"],
        tips: ["Regrows from root end", "Harvest continuously"],
        commonPests: ["Onion thrips"],
        commonDiseases: ["Downy mildew"],
    },

    // === HERBS ===
    basil: {
        id: "basil",
        name: "Basil",
        category: "herb",
        scientificName: "Ocimum basilicum",
        description: "Aromatic herb, great with tomatoes",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 20, max: 28 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 25,
        depthCm: 0.5,
        germinationDays: { min: 5, max: 10 },
        harvestDays: { min: 25, max: 40 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.15,
            fruiting: 0.15,
            mature: 0.1,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 23,
        nutritionHighlights: ["Vitamin K", "Essential oils"],
        goalFit: ["fast"],
        companions: ["tomato", "pepper"],
        avoid: ["sage"],
        tips: ["Pinch flowers to extend leaf production", "Sensitive to cold"],
        commonPests: ["Aphids", "Japanese beetles"],
        commonDiseases: ["Fusarium wilt", "Downy mildew"],
    },

    mint: {
        id: "mint",
        name: "Mint",
        category: "herb",
        scientificName: "Mentha",
        description: "Vigorous spreading herb",
        waterNeed: "medium",
        sunNeed: "partial-shade",
        preferredSoil: ["loamy", "any"],
        saltTolerance: "medium",
        minTemperatureC: -5,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 24 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 45,
        depthCm: 0.5,
        germinationDays: { min: 10, max: 15 },
        harvestDays: { min: 30, max: 60 },
        seasonalPlanting: ["spring", "summer", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.15,
            flowering: 0.15,
            fruiting: 0.15,
            mature: 0.1,
        },
        expectedYieldKg: 0.2,
        caloriesPer100g: 70,
        nutritionHighlights: ["Menthol", "Vitamin A"],
        goalFit: ["fast"],
        companions: ["cabbage", "tomato"],
        avoid: ["parsley"],
        tips: ["Grow in containers to prevent spreading", "Very invasive"],
        commonPests: ["Spider mites", "Aphids"],
        commonDiseases: ["Rust", "Powdery mildew"],
    },

    parsley: {
        id: "parsley",
        name: "Parsley",
        category: "herb",
        scientificName: "Petroselinum crispum",
        description: "Versatile culinary herb",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 22 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 20,
        depthCm: 0.5,
        germinationDays: { min: 14, max: 28 },
        harvestDays: { min: 60, max: 90 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 36,
        nutritionHighlights: ["Vitamin K", "Vitamin C", "Iron"],
        goalFit: ["nutrition"],
        companions: ["tomato", "asparagus"],
        avoid: ["lettuce", "mint"],
        tips: ["Slow to germinate", "Cut outer stems first"],
        commonPests: ["Carrot fly", "Aphids"],
        commonDiseases: ["Leaf spot"],
    },

    cilantro: {
        id: "cilantro",
        name: "Cilantro/Coriander",
        category: "herb",
        scientificName: "Coriandrum sativum",
        description: "Dual-use herb and spice",
        waterNeed: "medium",
        sunNeed: "partial-shade",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 5,
        maxTemperatureC: 25,
        optimalTemperatureC: { min: 10, max: 20 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 15,
        depthCm: 1,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 21, max: 45 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.1,
        caloriesPer100g: 23,
        nutritionHighlights: ["Vitamin K", "Vitamin A"],
        goalFit: ["fast"],
        companions: ["tomato", "spinach"],
        avoid: ["fennel"],
        tips: ["Bolts quickly in heat", "Seeds are coriander spice"],
        commonPests: ["Aphids"],
        commonDiseases: ["Powdery mildew"],
    },

    oregano: {
        id: "oregano",
        name: "Oregano",
        category: "herb",
        scientificName: "Origanum vulgare",
        description: "Mediterranean herb, perennial",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "medium",
        minTemperatureC: -10,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 30,
        depthCm: 0.5,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 45, max: 60 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.2,
        caloriesPer100g: 265,
        nutritionHighlights: ["Antioxidants", "Vitamin K"],
        goalFit: ["fast"],
        companions: ["pepper", "tomato"],
        avoid: [],
        tips: ["Drought tolerant once established", "Perennial in mild climates"],
        commonPests: ["Spider mites", "Aphids"],
        commonDiseases: ["Root rot"],
    },

    thyme: {
        id: "thyme",
        name: "Thyme",
        category: "herb",
        scientificName: "Thymus vulgaris",
        description: "Aromatic perennial herb",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "high",
        minTemperatureC: -10,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 30,
        depthCm: 0.5,
        germinationDays: { min: 14, max: 28 },
        harvestDays: { min: 60, max: 90 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.03,
            vegetative: 0.07,
            flowering: 0.08,
            fruiting: 0.08,
            mature: 0.05,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 101,
        nutritionHighlights: ["Vitamin C", "Iron", "Thymol"],
        goalFit: ["fast"],
        companions: ["cabbage", "tomato", "eggplant"],
        avoid: [],
        tips: ["Very drought tolerant", "Perennial in most climates"],
        commonPests: ["Spider mites"],
        commonDiseases: ["Root rot"],
    },

    rosemary: {
        id: "rosemary",
        name: "Rosemary",
        category: "herb",
        scientificName: "Salvia rosmarinus",
        description: "Woody, fragrant perennial herb",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "high",
        minTemperatureC: -5,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 18, max: 28 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 60,
        depthCm: 0.5,
        germinationDays: { min: 14, max: 28 },
        harvestDays: { min: 90, max: 180 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 131,
        nutritionHighlights: ["Antioxidants", "Iron", "Calcium"],
        goalFit: [],
        companions: ["beans", "cabbage", "carrot"],
        avoid: [],
        tips: ["Drought tolerant", "Can grow quite large"],
        commonPests: ["Spider mites", "Aphids"],
        commonDiseases: ["Powdery mildew", "Root rot"],
    },

    dill: {
        id: "dill",
        name: "Dill",
        category: "herb",
        scientificName: "Anethum graveolens",
        description: "Feathery herb for pickling",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "low",
        minTemperatureC: 10,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 15, max: 24 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 25,
        depthCm: 0.5,
        germinationDays: { min: 7, max: 14 },
        harvestDays: { min: 40, max: 60 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.1,
        caloriesPer100g: 43,
        nutritionHighlights: ["Vitamin A", "Vitamin C"],
        goalFit: ["fast"],
        companions: ["cabbage", "lettuce", "onion"],
        avoid: ["carrot"],
        tips: ["Attracts beneficial insects", "Self-seeds readily"],
        commonPests: ["Aphids", "Hornworms"],
        commonDiseases: ["Powdery mildew"],
    },

    chives: {
        id: "chives",
        name: "Chives",
        category: "herb",
        scientificName: "Allium schoenoprasum",
        description: "Mild onion-flavored herb",
        waterNeed: "medium",
        sunNeed: "partial-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: -5,
        maxTemperatureC: 28,
        optimalTemperatureC: { min: 12, max: 22 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 20,
        depthCm: 0.5,
        germinationDays: { min: 10, max: 21 },
        harvestDays: { min: 60, max: 90 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.15,
        caloriesPer100g: 30,
        nutritionHighlights: ["Vitamin K", "Vitamin C"],
        goalFit: ["fast"],
        companions: ["carrot", "tomato"],
        avoid: ["beans", "peas"],
        tips: ["Perennial, comes back yearly", "Edible flowers"],
        commonPests: ["Onion thrips"],
        commonDiseases: ["Rust"],
    },

    sage: {
        id: "sage",
        name: "Sage",
        category: "herb",
        scientificName: "Salvia officinalis",
        description: "Savory perennial herb",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "medium",
        minTemperatureC: -10,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "easy",
        spacingCm: 45,
        depthCm: 0.5,
        germinationDays: { min: 14, max: 21 },
        harvestDays: { min: 75, max: 90 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.05,
            vegetative: 0.1,
            flowering: 0.1,
            fruiting: 0.1,
            mature: 0.08,
        },
        expectedYieldKg: 0.2,
        caloriesPer100g: 315,
        nutritionHighlights: ["Vitamin K", "Antioxidants"],
        goalFit: [],
        companions: ["rosemary", "cabbage", "carrot"],
        avoid: ["basil", "cucumber"],
        tips: ["Drought tolerant once established", "Woody perennial"],
        commonPests: ["Spider mites", "Slugs"],
        commonDiseases: ["Powdery mildew"],
    },

    // === FRUITS ===
    strawberry: {
        id: "strawberry",
        name: "Strawberry",
        category: "fruit",
        scientificName: "Fragaria × ananassa",
        description: "Sweet berry, productive in small spaces",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: -5,
        maxTemperatureC: 30,
        optimalTemperatureC: { min: 15, max: 24 },
        spaceEfficiency: ["containers", "rooftop", "balcony", "backyard", "microplot"],
        difficulty: "medium",
        spacingCm: 30,
        depthCm: 0,
        germinationDays: { min: 7, max: 21 },
        harvestDays: { min: 60, max: 90 },
        seasonalPlanting: ["spring", "fall"],
        waterByStage: {
            seedling: 0.15,
            vegetative: 0.3,
            flowering: 0.5,
            fruiting: 0.6,
            mature: 0.4,
        },
        expectedYieldKg: 0.5,
        caloriesPer100g: 32,
        nutritionHighlights: ["Vitamin C", "Manganese", "Antioxidants"],
        goalFit: ["nutrition", "income"],
        companions: ["beans", "lettuce", "spinach"],
        avoid: ["cabbage", "broccoli"],
        tips: ["Remove runners for larger fruit", "Mulch to prevent soil contact"],
        commonPests: ["Slugs", "Birds", "Spider mites"],
        commonDiseases: ["Gray mold", "Powdery mildew"],
    },

    watermelon: {
        id: "watermelon",
        name: "Watermelon",
        category: "fruit",
        scientificName: "Citrullus lanatus",
        description: "Refreshing summer fruit",
        waterNeed: "high",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "low",
        minTemperatureC: 18,
        maxTemperatureC: 38,
        optimalTemperatureC: { min: 24, max: 32 },
        spaceEfficiency: ["backyard", "field"],
        difficulty: "medium",
        spacingCm: 180,
        depthCm: 2,
        germinationDays: { min: 4, max: 12 },
        harvestDays: { min: 70, max: 90 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.5,
            vegetative: 1.0,
            flowering: 1.5,
            fruiting: 2.0,
            mature: 0.8,
        },
        expectedYieldKg: 10,
        caloriesPer100g: 30,
        nutritionHighlights: ["Vitamin C", "Lycopene", "Hydration"],
        goalFit: ["nutrition"],
        companions: ["corn", "radish"],
        avoid: ["potato"],
        tips: ["Needs lots of space", "Reduce watering near harvest"],
        commonPests: ["Aphids", "Cucumber beetles"],
        commonDiseases: ["Fusarium wilt", "Anthracnose"],
    },

    cantaloupe: {
        id: "cantaloupe",
        name: "Cantaloupe/Melon",
        category: "fruit",
        scientificName: "Cucumis melo",
        description: "Sweet orange-fleshed melon",
        waterNeed: "high",
        sunNeed: "full-sun",
        preferredSoil: ["sandy", "loamy"],
        saltTolerance: "low",
        minTemperatureC: 18,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 24, max: 30 },
        spaceEfficiency: ["backyard", "field"],
        difficulty: "medium",
        spacingCm: 120,
        depthCm: 2,
        germinationDays: { min: 4, max: 10 },
        harvestDays: { min: 75, max: 95 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.4,
            vegetative: 0.8,
            flowering: 1.2,
            fruiting: 1.5,
            mature: 0.6,
        },
        expectedYieldKg: 3,
        caloriesPer100g: 34,
        nutritionHighlights: ["Vitamin A", "Vitamin C", "Potassium"],
        goalFit: ["nutrition"],
        companions: ["corn", "sunflower"],
        avoid: ["potato"],
        tips: ["Ripe when stem slips easily", "Needs warm soil"],
        commonPests: ["Aphids", "Cucumber beetles"],
        commonDiseases: ["Powdery mildew"],
    },

    grapes: {
        id: "grapes",
        name: "Grapes",
        category: "fruit",
        scientificName: "Vitis vinifera",
        description: "Perennial vine fruit",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "low",
        minTemperatureC: -15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 20, max: 30 },
        spaceEfficiency: ["backyard", "field"],
        difficulty: "hard",
        spacingCm: 200,
        depthCm: 10,
        germinationDays: { min: 14, max: 56 },
        harvestDays: { min: 365, max: 730 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.5,
            vegetative: 1.0,
            flowering: 1.2,
            fruiting: 1.5,
            mature: 0.8,
        },
        expectedYieldKg: 5,
        caloriesPer100g: 69,
        nutritionHighlights: ["Vitamin C", "Vitamin K", "Resveratrol"],
        goalFit: ["income"],
        companions: ["beans", "peas"],
        avoid: ["cabbage"],
        tips: ["Requires pruning", "Needs support structure"],
        commonPests: ["Japanese beetles", "Grape berry moth"],
        commonDiseases: ["Powdery mildew", "Downy mildew"],
    },

    // === GRAINS ===
    corn: {
        id: "corn",
        name: "Corn/Maize",
        category: "grain",
        scientificName: "Zea mays",
        description: "Staple grain, needs pollination",
        waterNeed: "medium",
        sunNeed: "full-sun",
        preferredSoil: ["loamy"],
        saltTolerance: "low",
        minTemperatureC: 15,
        maxTemperatureC: 35,
        optimalTemperatureC: { min: 20, max: 30 },
        spaceEfficiency: ["backyard", "microplot", "field"],
        difficulty: "medium",
        spacingCm: 25,
        depthCm: 5,
        germinationDays: { min: 5, max: 12 },
        harvestDays: { min: 60, max: 100 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.3,
            vegetative: 0.6,
            flowering: 1.0,
            fruiting: 1.0,
            mature: 0.4,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 86,
        nutritionHighlights: ["Fiber", "Vitamin B6", "Phosphorus"],
        goalFit: ["calories"],
        companions: ["beans", "squash", "pumpkin"],
        avoid: ["tomato"],
        tips: ["Plant in blocks for pollination", "Part of Three Sisters"],
        commonPests: ["Corn earworm", "Corn borer"],
        commonDiseases: ["Corn smut", "Rust"],
    },

    quinoa: {
        id: "quinoa",
        name: "Quinoa",
        category: "grain",
        scientificName: "Chenopodium quinoa",
        description: "High-protein pseudo-grain",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "high",
        minTemperatureC: 5,
        maxTemperatureC: 32,
        optimalTemperatureC: { min: 15, max: 25 },
        spaceEfficiency: ["backyard", "microplot", "field"],
        difficulty: "medium",
        spacingCm: 25,
        depthCm: 1,
        germinationDays: { min: 3, max: 7 },
        harvestDays: { min: 90, max: 120 },
        seasonalPlanting: ["spring"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.2,
            flowering: 0.3,
            fruiting: 0.25,
            mature: 0.1,
        },
        expectedYieldKg: 0.2,
        caloriesPer100g: 368,
        nutritionHighlights: ["Complete protein", "Fiber", "Iron"],
        goalFit: ["calories", "nutrition"],
        companions: [],
        avoid: [],
        tips: ["Very drought tolerant", "Rinse before eating"],
        commonPests: ["Aphids"],
        commonDiseases: ["Downy mildew"],
    },

    amaranth: {
        id: "amaranth",
        name: "Amaranth",
        category: "grain",
        scientificName: "Amaranthus",
        description: "Dual-use: grain and leafy green",
        waterNeed: "low",
        sunNeed: "full-sun",
        preferredSoil: ["loamy", "sandy"],
        saltTolerance: "medium",
        minTemperatureC: 15,
        maxTemperatureC: 38,
        optimalTemperatureC: { min: 20, max: 30 },
        spaceEfficiency: ["backyard", "microplot", "field"],
        difficulty: "easy",
        spacingCm: 30,
        depthCm: 0.5,
        germinationDays: { min: 3, max: 10 },
        harvestDays: { min: 90, max: 120 },
        seasonalPlanting: ["spring", "summer"],
        waterByStage: {
            seedling: 0.1,
            vegetative: 0.2,
            flowering: 0.3,
            fruiting: 0.25,
            mature: 0.1,
        },
        expectedYieldKg: 0.3,
        caloriesPer100g: 371,
        nutritionHighlights: ["Protein", "Iron", "Calcium"],
        goalFit: ["calories", "nutrition"],
        companions: ["corn"],
        avoid: [],
        tips: ["Leaves edible as greens", "Heat tolerant"],
        commonPests: ["Aphids", "Flea beetles"],
        commonDiseases: ["Root rot"],
    },
};

// Utility functions
export function getPlantById(id: string): PlantData | undefined {
    return PLANTS[id];
}

export function getPlantsByCategory(category: PlantCategory): PlantData[] {
    return Object.values(PLANTS).filter((p) => p.category === category);
}

export function getPlantsByDifficulty(difficulty: Difficulty): PlantData[] {
    return Object.values(PLANTS).filter((p) => p.difficulty === difficulty);
}

export function getPlantsByWaterNeed(waterNeed: WaterNeed): PlantData[] {
    return Object.values(PLANTS).filter((p) => p.waterNeed === waterNeed);
}

export function getPlantsByGoal(goal: Goal): PlantData[] {
    return Object.values(PLANTS).filter((p) => p.goalFit.includes(goal));
}

export function getPlantsForSpace(space: GrowingSpace): PlantData[] {
    return Object.values(PLANTS).filter((p) => p.spaceEfficiency.includes(space));
}

export function getAllPlants(): PlantData[] {
    return Object.values(PLANTS);
}

export function getPlantByName(name: string): PlantData | undefined {
    const normalizedName = name.toLowerCase().trim();
    return Object.values(PLANTS).find((p) => 
        p.name.toLowerCase() === normalizedName ||
        p.id === normalizedName ||
        p.id === normalizedName.replace(/\s+/g, "-")
    );
}

export function getPlantOptions(): { value: string; label: string }[] {
    return Object.entries(PLANTS).map(([id, plant]) => ({
        value: id,
        label: plant.name,
    }));
}

// Calculate daily water for a plant at a specific stage
export function calculatePlantWater(
    plantId: string,
    stage: GrowthStage,
    plantCount: number
): number {
    const plant = PLANTS[plantId];
    if (!plant) return 0;
    return plant.waterByStage[stage] * plantCount;
}

// Get category display name
export const CATEGORY_LABELS: Record<PlantCategory, string> = {
    vegetable: "Vegetables",
    fruit: "Fruits",
    legume: "Legumes",
    root: "Root Vegetables",
    herb: "Herbs",
    "leafy-green": "Leafy Greens",
    grain: "Grains",
    tuber: "Tubers",
};
